#### 1) Найти с помощью NumPy SVD

In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=2, suppress=True)

In [3]:
A = [[1,2,0],
     [0,0,5],
     [3,-4,2],
     [1,6,5],
     [0,1,0]
    ]
A = np.array(A)

In [4]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
print(f'Матрица U: \n{U}')

Матрица U: 
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [6]:
print(f'Матрица D: \n{D}')

Матрица D: 
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [7]:
print(f'Матрица V: \n{V}')

Матрица V: 
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


#### Для матрицы из предыдущего задания найти:

##### а) евклидову норму;

In [8]:
print(f'Евклидова норма равна максимальному сингулярному числу {s[0]}')

Евклидова норма равна максимальному сингулярному числу 8.824868854820442


##### б) норму Фробениуса.

In [9]:
sum = 0
for item in s:
    sum += pow(item, 2)

In [11]:
print(f'Норма Фробениуса равна {pow(sum, 0.5)}')

Норма Фробениуса равна 11.045361017187261
